# Generated by Django 4.0 on 2021-12-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('reference', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('subtype', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('material', models.CharField(max_length=255)),
                ('form', models.CharField(max_length=255)),
                ('release_date', models.DateField(null=True)),
                ('images', models.CharField(max_length=255)),
            ],
        ),
    ]
