# Generated by Django 4.0 on 2022-02-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='reference',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
